server:
  port: 9000
  servlet:
    session:
      tracking-modes: cookie
spring:
  profiles:
    active: h2
  application:
    name: id-server
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database: mysql