spring:
  datasource:
    url: jdbc:mysql://localhost:3306/id_server_database
    username: root
    password: 123456
logging:
  level:
    org.springframework.web: trace
    org.springframework.security.oauth2: debug
    org.springframework.jdbc.core: debug
    org.springframework.security: trace