server:
  port: 9000
spring:
  profiles:
    active: h2
  application:
    name: id-server
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database: mysql