server:
  port: 9000
spring:
  application:
    name: id-server
  datasource:
    url: jdbc:mysql://localhost:3306/id_server_database
    username: root
    password: 123456
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.web: trace
    org.springframework.security.oauth2: debug
    org.springframework.jdbc.core: debug